agent_name: base
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeieodkqjtplehpjt76cfzv3wsr5hw257o7uojcx3sc2n4e72cylxga
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeigo2eqc3fsx4hxts5zq77q6hgvcdzem5e3yxn4lk6el6xjcvhheba
- eightballer/http_server:0.1.0:bafybeicuooiamxoox5nhwmlzel2cq5znsfmvb6t5wddmnmpznblwkpvkle
- eightballer/prometheus:0.1.1:bafybeiabjyx2p5zrrvgxqgfzdr34ulcqaozy564dvhfjf76itlaid6eoke
contracts: []
protocols:
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeic4hfdvhnn36gyddw3usonjfyiqmckxkeaoh2pz5y3nxsat7dc4bq
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
skills:
- eightballer/metrics:0.1.0:bafybeifbfkhlh4ct5vcrjcrlhdcqcswxy3rngb37sbmjnccenolzpc3pfe
- eightballer/prometheus:0.1.0:bafybeiameg4uy73z3m4nmwuz5cotkdbpedvju33kjs7ky43ccnfxbnayiy
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
  open-aea-ledger-cosmos: {}
  rich: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: eightballer/metrics:0.1.0
